name: checking python code using linting

on:
  workflow_dispatch:

jobs:
  linting_code:
      runs-on: ubuntu-latest
      steps:
          - name: code checkout
            uses: actions/checkout@v4

          - name: setup python 3.13
            uses: actions/setup-python@v6
            with:
              python-version: 3.13

          - name: installing dependencies
            run: pip install -r requirements.txt

          - name: checking code via flake 8
            run: flake app.py
