name: devsecops pipeline
on:
  workflow_dispatch:
jobs:
  linting:
      uses: ./.github/workflows/code-check-lint.yml
  secrets-scan:
      uses: ./.github/workflows/secrets-scan.yml
  depe-scan:
      uses: ./.github/workflows/dependancies-scan.yml
  dockerfile-scan:
      uses: ./.github/workflows/dockerfile-scan.yml
  build-push:
      needs: [linting,secrets-scan,depe-scan,dockerfile-scan]
      uses: ./.github/workflows/build-and-push.yml
      secrets: inherit
  docker-image-scan:
      needs: [build-push]
      uses: ./.github/workflows/trivy-scan.yml
      secrets: inherit

    
