name: devsecops pipeline
on:
  workflow_dispatch:
jobs:
  linting:
      uses: ./.github/workflows/code-check-lint.yml
  secrets-scan:
      uses: ./.github/workflows/secrets-scan.yml
  depe-scan:
      uses: ./.github/workflows/dependancies-scan.yml
  build-push:
      uses: ./.github/workflows/build-and-push.yml
      secrets: inherit
  docker-image-scan:
      uses: ./.github/workflows/trivy-scan.yml
      secrets: inherit

    
